server:
  port: 8082
spring:
  application:
    name: capacitacion
  datasource:
    url: jdbc:postgresql://localhost:5432/capacitacion_erp
    username: postgres
    password: sisapp98
    driver-class-name: org.postgresql.Driver
